version: '3.1'
volumes:
  data:
    external:
      name: mongo-web-services-volume
services:
  noca-mongo:
    build: 
      context: .
      dockerfile: "Dockerfile"
    image: noca-mongo
    ports:
     - '3006:3005'
    environment:
      MONGO_URI: 'mongodb://root:example@mongo:27017/unlz?authSource=admin'
      NODE_ENV: docker
      URLDB: 'mongodb://root:example@mongo:27017/unlz?authSource=admin'
    depends_on:
    - mongo
  mongo:
    image: mongo
    restart: always
    ports:
    - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - data:/data/db